### ISSUE TITLE
In what way is the pagination component responsive?

### ISSUE THREAD

**Issue by thehappycoder** [unleashit/npm-library#9]
Does it render depending on the width of the container?

**Comment by unleashit** [comment]
The algo is not the best on the planet, but yes indeed. It works pretty well, but if you're aesthetically picky like me, sometimes there's a margin on the right side (between the last page and the "next" button" when there are more pages than will fit. It's pretty subtle, but since you brought it up...

This is the one component in the repo that I pulled from an older project and never updated. It's tested and works OK but make sure to test it in your environment if you use on anything important. It's on the back burner to give it some polish but I'm not sure when.

**Comment by thehappycoder** [comment]
@unleashit 
Thank you for the demo link! I can see the gap is quite big 
<img width="1342" alt="Screen Shot 2020-06-15 at 8 35 39 am" src="https://user-images.githubusercontent.com/60022/84605768-482ded00-aee3-11ea-835c-15f14eb86ffb.png">

I've found another responsive library that isn't polished but works ok so far after I tweaked it a bit in my fork https://github.com/jonelantha/react-responsive-pagination It leaves small gaps too but is able to fill the available space quite well. One downside is that one needs to pass maxWidth property to it.

**Comment by unleashit** [comment]
Cool, I'll close this then. FYI, with a tiny bit of CSS you could get rid of the gap (either remove the margin-left on the "next" or justify the numbers all the way across). At the time I did it, on wider screens I actually preferred that look over filling it full of pages. The only place it slightly bothers me is some mobile sizes that could an adjustment up/down on the number of pages.
